{% set version = "0.8.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-locpol
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/locpol_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/locpol/locpol_{{ version }}.tar.gz
  sha256: b37f62c69995d8b856bd3eb418b9605e0cbddc9f6ccc9d4960dcb659484f37ae

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('locpol')"           # [not win]
    - "\"%R%\" -e \"library('locpol')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=locpol
  license: GPL-2.0-or-later
  summary: Computes local polynomial estimators for  the regression and also density. It comprises several  different utilities to handle kernel estimators.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: locpol
# Version: 0.7-0
# Date: 2018-05-21
# Title: Kernel Local Polynomial Regression
# Author: Jorge Luis Ojeda Cabrera <jojeda@unizar.es>
# Maintainer: Jorge Luis Ojeda Cabrera <jojeda@unizar.es>
# Description: Computes local polynomial estimators for  the regression and also density. It comprises several  different utilities to handle kernel estimators.
# Depends: R (>= 2.5.0), graphics, stats
# License: GPL (>= 2)
# NeedsCompilation: yes
# Packaged: 2018-05-24 12:44:38 UTC; jorge
# Repository: CRAN
# Date/Publication: 2018-05-24 17:28:06 UTC
