travis:
  secure:
    BINSTAR_TOKEN: qDmDkw2HzIJ6i9Qlz02ddQ5aaF29jDsxc+Pw+vtCjceQ5qV+ulrnVeARJHnCoomSfMpFEJRXzg4F05/YhZf9s1pFTP6Mw8ke2YWkejeRvoATecWi64wJ4Uht/3KpGpOAGYUomf4vyzWAfbTyetG4muiybbKvoPvNVrMVM5S01b+x5rC3rX26yFYUivEIikKiTQxCxy9KdlnPN8160k/67gklHV7EyJIzv0smQpMk8jCSryO8JdGYkENi7SlR23RscXtZ7/m8+0+1fWyrJ5ovAoaE+Vt1AiqUT1/gvkYPkMUwh/qmxbDGnSNFr/klKqDLqsnBiOoLfvxJJuB4dT8Nkl0bIrRNIeUMr07BzXe/pzrSMDSN8h76jqS5cksRCYeYCBwJ7LNamkKPT/zamHwAthb9AC2aiTg5UcSA+yUfrMC5h8oFkhKNsPFu1nhsak7SdxiwtfNiZoe3maEvTnM0Av5R+lTNFTLzVGZTHYUp93od4gnj3019JlY/YxTOdN5c3v5Ykl0+AxBc7j2kginud/2SbUUVAP0Om2ZMnfHjel+shKvMb8Lz1mMwiSUtq6pRWxPTyDUA0G38t/NK2vRgWObuXUJ2O8ktEhm48IQW/tf+mppbXqsDE8qrP48m5cZoAG2KJJg2/pugTcSaLADo4bsLybz7rAiByi7vJufZqLQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
